[package]
name = "efficient_pca"
version = "0.1.2"
authors = ["Erik Garrison <erik.garrison@gmail.com>, SauersML"]
edition = "2021"
description = "Principal component computation using SVD and covariance matrix trick"
license = "MIT"
repository = "https://github.com/SauersML/efficient_pca"
readme = "README.md"
keywords = ["statistics", "PCA"]
categories = ["science"]
documentation = "https://github.com/SauersML/efficient_pca"

[dependencies]
float-cmp = "0.10.0"
ndarray = "0.16.1"
ndarray-linalg = { version = "0.17.0", features = ["openblas-static"] }
ndarray-rand = "0.15.0"
rand = "0.8"
rand_chacha = "0.9.0"
sysinfo = "0.33.1"
rand_distr = "0.5.1"
tempfile = "3.18.0"

[lib]
name = "efficient_pca"
path = "src/lib.rs"
